### ISSUE TITLE
Compatible with gatekeeper (Captcha)?

### ISSUE THREAD

**Issue by slimeyoctopus** [tonyboylehub/candymachine-v2-boiler-mint-site-noFLP#1]
Hey Tony, thanks for this awesome looking front end.
I have tested the token and WL functionality and it works perfectly.  Just wondered if there is any support for cadymachines that are using the gatekeeper (Captcha) feature?  I can see items relating to it in the `utils.ts` file but I think these are remnants from the Metaplex FLP front-end.
I assume that's why it fails to load the number of tokens available to mint and the mint fails?
Thanks again

![front_end_issue](https://user-images.githubusercontent.com/97131586/148131143-fb34cc4a-3178-45ae-b51b-83ac2f13fe1d.gif)

**Comment by tonyboylehub** [comment]
hey bud :)

Fixed the lower left, that was some logic that went a bit awol. That was pushed up and merged this evening.

Last time I checked gatekeeper was still working as far as I know. I tested and it was loading up fine.

In regards to your video and your transaction failing my site actually has no authority over that. The UI of the boiler only enables the button to interact with the wallet so there is possibly a candymachine config error in regards to burning the whitelist token and minting. The site is showing you have 50 whitelist tokens in your wallet though it seems.

Generally if the mint fails like that its because the candy machine is not live in the actual candymachine config and you get the failed 0.00001 Sol cost error.

**Comment by slimeyoctopus** [comment]
Hey Tony, 
Thanks for coming back so quick.  I can see the number of mints left (x/x) works as expected now :)

I'm still facing the issue when gatekeeper and WL are enabled together.  Here's what I have found from my testing:

CM Config: Presale disabled, gateway enabled 
Result: Captcha presented, can mint as expected 

CM Config: Presale enabled, gateway disabled 
Result: No Captcha presented, Can mint as expected, presale token deducted from balance

CM Config: Presale enabled, gateway enabled 
Result: Captcha not presented, mint fails
*This is what is demonstrated in my GIF above
Have you tested this use case successfully?

It is possible the CMv2 config is misconfigured. But I'm pretty sure it isn't as all of the other test cases work as expected.
I'd be happy to share my config with you privately if you wanted.

And this isn't a massive issue, I can work around it by not using the gateway for presale (as the tokens would stop the bots) and then re-enabling it for public sale.

Also, just an improvement suggestion :) - when the mints to claim == 0 I think it would be good if the mint button was disabled.

Thanks again for your work and help with this.

**Comment by tonyboylehub** [comment]
Hi bud, I just tested it my end and it seems to be working fine. If you're in the Discord can you send me a PM? and we can get to the bottom of this.

<img width="1276" alt="Screenshot 2022-01-05 at 12 31 21" src="https://user-images.githubusercontent.com/81017245/148218195-e9bbcbdd-5b9b-4ef3-8b67-62b874538749.png">

**Comment by slimeyoctopus** [comment]
Hey Tony, that would be great, thanks :)
I don't have the discord link. Please can you send me an invite.  Happy to delete this thread after, so it's not public.

I have DM'd you on twitter if you don't want to share the link here.

Thanks

**Comment by tonyboylehub** [comment]
This is the Metaplex discord link we are all in. Good bunch of people and I'm in here daily.

https://discord.gg/25WemxhQ

**Comment by slimeyoctopus** [comment]
Amazing thanks, just joined.  Since I know it's an issue my end, I'll try to troubleshoot myself first so I'm not bothering you.  Will give you a shout if I can't figure it out.
Thanks again 👍

**Comment by tonyboylehub** [comment]
Don't be silly, gimmie a shout man! Let's have a look, happy to help :D
I'm Tonyboyle.sol in the discord but my discord user name is TonyBoyle.eth#0265
